### PR TITLE
quote csv output

### LINKED ISSUE #19: app chokes on payee names with a ","
payee names with a "," in the source csv confuse the app, and all columns for that row get right shifted by one (as the payee name is split over two columns"

here's a sample row of data, for testing:

```
"2016-11-19","FOOBAR, INC.","","MasterCard Payment","","Miscellaneous","-23.57","","",""
```

would you be interested in a pull request that fixes this issue?

### PR DESCRIPTION
**Pull request by nomicode**
this fixes #19

### CODE REVIEW

**Comment by hjhart** [comment]
Just found this tool and encountered this problem. Seems like quoting the output is a good option to me as well.

**Comment by nomicode** [comment]
@hjhart if you like you can use the app on my fork

https://nslater.github.io/ynab-csv/

**Comment by hjhart** [comment]
@nslater Yes, I actually already did that! 👍 

Should be helpful for other people who experience this issue. Thanks for the fix.

**Comment by nomicode** [comment]
@hjhart you're welcome!

**Comment by jcranky** [comment]
@nslater thanks for that, I got hit by the same problem :)
@halloffame any reason this can't be merged here?

**Comment by nomicode** [comment]
closing due to lack of response

**Pull request closed without merging**
